const translationBlocks = [
  // --- УРОВЕНЬ 1: НАЧИНАЮЩИЙ (Present Simple / Continuous) ---
  [
    {
      russian: "Я люблю читать книги.",
      english: "I love to read books.",
      negative: "I don't love to read books.",
      interrogative: "Do I love to read books?",
    },
    {
      russian: "Она играет на пианино.",
      english: "She plays the piano.",
      negative: "She doesn't play the piano.",
      interrogative: "Does she play the piano?",
    },
    {
      russian: "Они говорят по-испански.",
      english: "They speak Spanish.",
      negative: "They don't speak Spanish.",
      interrogative: "Do they speak Spanish?",
    },
    {
      russian: "Мы работаем в офисе.",
      english: "We work in an office.",
      negative: "We don't work in an office.",
      interrogative: "Do we work in an office?",
    },
    {
      russian: "Он ест яблоко.",
      english: "He is eating an apple.",
      negative: "He is not eating an apple.",
      interrogative: "Is he eating an apple?",
    },
    {
      russian: "Ты смотришь фильм.",
      english: "You are watching a movie.",
      negative: "You are not watching a movie.",
      interrogative: "Are you watching a movie?",
    },
    {
      russian: "Она готовит ужин.",
      english: "She is cooking dinner.",
      negative: "She is not cooking dinner.",
      interrogative: "Is she cooking dinner?",
    },
    {
      russian: "Я иду в школу.",
      english: "I am going to school.",
      negative: "I am not going to school.",
      interrogative: "Am I going to school?",
    },
    {
      russian: "Они пьют воду.",
      english: "They are drinking water.",
      negative: "They are not drinking water.",
      interrogative: "Are they drinking water?",
    },
    {
      russian: "Он пишет письмо.",
      english: "He is writing a letter.",
      negative: "He is not writing a letter.",
      interrogative: "Is he writing a letter?",
    },
  ],
  [
    {
      russian: "Она купила новую машину.",
      english: "She bought a new car.",
      negative: "She didn't buy a new car.",
      interrogative: "Did she buy a new car?",
    },
    {
      russian: "Мы ходили в кино вчера.",
      english: "We went to the cinema yesterday.",
      negative: "We didn't go to the cinema yesterday.",
      interrogative: "Did we go to the cinema yesterday?",
    },
    {
      russian: "Он закончил свой проект.",
      english: "He finished his project.",
      negative: "He didn't finish his project.",
      interrogative: "Did he finish his project?",
    },
    {
      russian: "Я встретил своего друга.",
      english: "I met my friend.",
      negative: "I didn't meet my friend.",
      interrogative: "Did I meet my friend?",
    },
    {
      russian: "Они жили в Париже.",
      english: "They lived in Paris.",
      negative: "They didn't live in Paris.",
      interrogative: "Did they live in Paris?",
    },
    {
      russian: "Она забыла свой телефон.",
      english: "She forgot her phone.",
      negative: "She didn't forget her phone.",
      interrogative: "Did she forget her phone?",
    },
    {
      russian: "Ты видел эту картину?",
      english: "You saw this painting.",
      negative: "You didn't see this painting.",
      interrogative: "Did you see this painting?",
    },
    {
      russian: "Мы говорили по телефону.",
      english: "We spoke on the phone.",
      negative: "We didn't speak on the phone.",
      interrogative: "Did we speak on the phone?",
    },
    {
      russian: "Я написал письмо.",
      english: "I wrote a letter.",
      negative: "I didn't write a letter.",
      interrogative: "Did I write a letter?",
    },
    {
      russian: "Он пришёл домой поздно.",
      english: "He came home late.",
      negative: "He didn't come home late.",
      interrogative: "Did he come home late?",
    },
  ],
  [
    {
      russian: "Я буду путешествовать.",
      english: "I will travel.",
      negative: "I will not travel.",
      interrogative: "Will I travel?",
    },
    {
      russian: "Она пойдёт на вечеринку.",
      english: "She will go to the party.",
      negative: "She will not go to the party.",
      interrogative: "Will she go to the party?",
    },
    {
      russian: "Они увидят новый фильм.",
      english: "They will see a new movie.",
      negative: "They will not see a new movie.",
      interrogative: "Will they see a new movie?",
    },
    {
      russian: "Он поможет тебе.",
      english: "He will help you.",
      negative: "He will not help you.",
      interrogative: "Will he help you?",
    },
    {
      russian: "Мы начнём завтра.",
      english: "We will start tomorrow.",
      negative: "We will not start tomorrow.",
      interrogative: "Will we start tomorrow?",
    },
    {
      russian: "Ты сдашь экзамен.",
      english: "You will pass the exam.",
      negative: "You will not pass the exam.",
      interrogative: "Will you pass the exam?",
    },
    {
      russian: "Она купит билеты.",
      english: "She will buy tickets.",
      negative: "She will not buy tickets.",
      interrogative: "Will she buy tickets?",
    },
    {
      russian: "Я позвоню тебе.",
      english: "I will call you.",
      negative: "I will not call you.",
      interrogative: "Will I call you?",
    },
    {
      russian: "Они приедут скоро.",
      english: "They will arrive soon.",
      negative: "They will not arrive soon.",
      interrogative: "Will they arrive soon?",
    },
    {
      russian: "Он прочитает книгу.",
      english: "He will read the book.",
      negative: "He will not read the book.",
      interrogative: "Will he read the book?",
    },
  ],
  [
    {
      russian: "Я был счастлив.",
      english: "I was happy.",
      negative: "I was not happy.",
      interrogative: "Was I happy?",
    },
    {
      russian: "Она была занята.",
      english: "She was busy.",
      negative: "She was not busy.",
      interrogative: "Was she busy?",
    },
    {
      russian: "Они были в парке.",
      english: "They were in the park.",
      negative: "They were not in the park.",
      interrogative: "Were they in the park?",
    },
    {
      russian: "Мы были готовы.",
      english: "We were ready.",
      negative: "We were not ready.",
      interrogative: "Were we ready?",
    },
    {
      russian: "Он был врачом.",
      english: "He was a doctor.",
      negative: "He was not a doctor.",
      interrogative: "Was he a doctor?",
    },
    {
      russian: "Ты был дома.",
      english: "You were at home.",
      negative: "You were not at home.",
      interrogative: "Were you at home?",
    },
    {
      russian: "Она была здесь.",
      english: "She was here.",
      negative: "She was not here.",
      interrogative: "Was she here?",
    },
    {
      russian: "Я был студентом.",
      english: "I was a student.",
      negative: "I was not a student.",
      interrogative: "Was I a student?",
    },
    {
      russian: "Они были друзьями.",
      english: "They were friends.",
      negative: "They were not friends.",
      interrogative: "Were they friends?",
    },
    {
      russian: "Он был высоким.",
      english: "He was tall.",
      negative: "He was not tall.",
      interrogative: "Was he tall?",
    },
  ],
  [
    {
      russian: "Я умею плавать.",
      english: "I can swim.",
      negative: "I cannot swim.",
      interrogative: "Can I swim?",
    },
    {
      russian: "Она может танцевать.",
      english: "She can dance.",
      negative: "She cannot dance.",
      interrogative: "Can she dance?",
    },
    {
      russian: "Они могут говорить.",
      english: "They can talk.",
      negative: "They cannot talk.",
      interrogative: "Can they talk?",
    },
    {
      russian: "Мы можем бежать.",
      english: "We can run.",
      negative: "We cannot run.",
      interrogative: "Can we run?",
    },
    {
      russian: "Он может водить машину.",
      english: "He can drive a car.",
      negative: "He cannot drive a car.",
      interrogative: "Can he drive a car?",
    },
    {
      russian: "Ты можешь мне помочь?",
      english: "You can help me.",
      negative: "You cannot help me.",
      interrogative: "Can you help me?",
    },
    {
      russian: "Она может петь.",
      english: "She can sing.",
      negative: "She cannot sing.",
      interrogative: "Can she sing?",
    },
    {
      russian: "Я могу играть на гитаре.",
      english: "I can play the guitar.",
      negative: "I cannot play the guitar.",
      interrogative: "Can I play the guitar?",
    },
    {
      russian: "Они могут прыгать.",
      english: "They can jump.",
      negative: "They cannot jump.",
      interrogative: "Can they jump?",
    },
    {
      russian: "Он может летать.",
      english: "He can fly.",
      negative: "He cannot fly.",
      interrogative: "Can he fly?",
    },
  ],
  // --- УРОВЕНЬ 2: СРЕДНИЙ (Perfect Tenses, Conditionals) ---
  [
    {
      russian: "Я уже пообедал.",
      english: "I have already had lunch.",
      negative: "I have not had lunch yet.",
      interrogative: "Have you had lunch yet?",
    },
    {
      russian: "Она только что пришла.",
      english: "She has just arrived.",
      negative: "She has not arrived yet.",
      interrogative: "Has she arrived yet?",
    },
    {
      russian: "Мы уже видели этот фильм.",
      english: "We have already seen this movie.",
      negative: "We have not seen this movie yet.",
      interrogative: "Have you seen this movie yet?",
    },
    {
      russian: "Я учил английский два года.",
      english: "I have been studying English for two years.",
      negative: "I have not been studying English for two years.",
      interrogative: "Have you been studying English for two years?",
    },
    {
      russian: "Они работали с 9 утра.",
      english: "They have been working since 9 a.m.",
      negative: "They have not been working since 9 a.m.",
      interrogative: "Have they been working since 9 a.m.?",
    },
    {
      russian: "Если ты придёшь, мы пойдём в кино.",
      english: "If you come, we will go to the cinema.",
      negative: "If you don't come, we won't go to the cinema.",
      interrogative: "If you come, will we go to the cinema?",
    },
    {
      russian: "Если бы у меня были деньги, я бы купил машину.",
      english: "If I had money, I would buy a car.",
      negative: "If I didn't have money, I wouldn't buy a car.",
      interrogative: "If you had money, would you buy a car?",
    },
    {
      russian: "Он закончил работу к 6 вечера.",
      english: "He had finished the work by 6 p.m.",
      negative: "He had not finished the work by 6 p.m.",
      interrogative: "Had he finished the work by 6 p.m.?",
    },
    {
      russian: "Я знаю её с детства.",
      english: "I have known her since childhood.",
      negative: "I have not known her since childhood.",
      interrogative: "Have you known her since childhood?",
    },
    {
      russian: "Она никогда не была в Японии.",
      english: "She has never been to Japan.",
      negative: "She has been to Japan.",
      interrogative: "Has she ever been to Japan?",
    },
  ],
  [
    {
      russian: "Я бы позвонил тебе, если бы у меня был твой номер.",
      english: "I would call you if I had your number.",
      negative: "I wouldn't call you if I didn't have your number.",
      interrogative: "Would you call me if you had my number?",
    },
    {
      russian: "Они обещали прийти.",
      english: "They promised to come.",
      negative: "They didn't promise to come.",
      interrogative: "Did they promise to come?",
    },
    {
      russian: "Она сказала, что она была здесь.",
      english: "She said that she had been here.",
      negative: "She didn't say that she had been here.",
      interrogative: "Did she say that she had been here?",
    },
    {
      russian: "Мы должны были встретиться в 5.",
      english: "We were supposed to meet at 5.",
      negative: "We were not supposed to meet at 5.",
      interrogative: "Were we supposed to meet at 5?",
    },
    {
      russian: "Мне пришлось уйти рано.",
      english: "I had to leave early.",
      negative: "I didn't have to leave early.",
      interrogative: "Did you have to leave early?",
    },
    {
      russian: "Он должен был знать ответ.",
      english: "He should have known the answer.",
      negative: "He shouldn't have known the answer.",
      interrogative: "Should he have known the answer?",
    },
    {
      russian: "Я решил выучить испанский.",
      english: "I have decided to learn Spanish.",
      negative: "I have not decided to learn Spanish.",
      interrogative: "Have you decided to learn Spanish?",
    },
    {
      russian: "Ты будешь читать, когда я позвоню?",
      english: "Will you be reading when I call?",
      negative: "Will you not be reading when I call?",
      interrogative: "Will you be reading when I call?",
    },
    {
      russian: "Они уже закончили к тому времени.",
      english: "They will have finished by then.",
      negative: "They will not have finished by then.",
      interrogative: "Will they have finished by then?",
    },
    {
      russian: "Она не смогла прийти.",
      english: "She was not able to come.",
      negative: "She was able to come.",
      interrogative: "Was she able to come?",
    },
  ],
  [
    {
      russian: "Я только что закончил готовить.",
      english: "I have just finished cooking.",
      negative: "I have not just finished cooking.",
      interrogative: "Have you just finished cooking?",
    },
    {
      russian: "Он ремонтировал машину весь день.",
      english: "He has been repairing the car all day.",
      negative: "He has not been repairing the car all day.",
      interrogative: "Has he been repairing the car all day?",
    },
    {
      russian: "Если бы он был здесь, он бы помог.",
      english: "If he were here, he would help.",
      negative: "If he were not here, he would not help.",
      interrogative: "If he were here, would he help?",
    },
    {
      russian: "Ты знал, что она переехала?",
      english: "Did you know that she had moved?",
      negative: "Didn't you know that she had moved?",
      interrogative: "Did you know that she had moved?",
    },
    {
      russian: "Мы будем работать над этим проектом завтра.",
      english: "We will be working on this project tomorrow.",
      negative: "We will not be working on this project tomorrow.",
      interrogative: "Will you be working on this project tomorrow?",
    },
    {
      russian: "Я ходил за покупками перед приходом гостей.",
      english: "I had gone shopping before the guests arrived.",
      negative: "I had not gone shopping before the guests arrived.",
      interrogative: "Had you gone shopping before the guests arrived?",
    },
    {
      russian: "Он сказал, что видел это.",
      english: "He said he had seen it.",
      negative: "He didn't say he had seen it.",
      interrogative: "Did he say he had seen it?",
    },
    {
      russian: "Я буду жить в этом городе уже 10 лет в следующем году.",
      english: "I will have been living in this city for 10 years next year.",
      negative:
        "I will not have been living in this city for 10 years next year.",
      interrogative:
        "Will you have been living in this city for 10 years next year?",
    },
    {
      russian: "Она должна была быть уже здесь.",
      english: "She should have been here already.",
      negative: "She shouldn't have been here yet.",
      interrogative: "Should she have been here already?",
    },
    {
      russian: "Я мог бы помочь тебе, но был занят.",
      english: "I could have helped you, but I was busy.",
      negative: "I could not have helped you, as I was busy.",
      interrogative: "Could you have helped me?",
    },
  ],
  [
    {
      russian: "Я уже поел, когда ты позвонил.",
      english: "I had already eaten when you called.",
      negative: "I had not eaten yet when you called.",
      interrogative: "Had you already eaten when I called?",
    },
    {
      russian: "Она говорила, пока я писал.",
      english: "She was talking while I was writing.",
      negative: "She was not talking while I was writing.",
      interrogative: "Was she talking while you were writing?",
    },
    {
      russian: "Если бы я был тобой, я бы купил это.",
      english: "If I were you, I would buy it.",
      negative: "If I were not you, I would not buy it.",
      interrogative: "If you were me, would you buy it?",
    },
    {
      russian: "Мы будем делать это весь день.",
      english: "We will be doing this all day.",
      negative: "We won't be doing this all day.",
      interrogative: "Will you be doing this all day?",
    },
    {
      russian: "Он выглядел так, будто не спал.",
      english: "He looked as if he hadn't slept.",
      negative: "He didn't look as if he hadn't slept.",
      interrogative: "Did he look as if he hadn't slept?",
    },
    {
      russian: "Мне кажется, она уже ушла.",
      english: "I think she has already left.",
      negative: "I don't think she has already left.",
      interrogative: "Do you think she has already left?",
    },
    {
      russian: "Они обещали, что позвонят.",
      english: "They promised that they would call.",
      negative: "They didn't promise that they would call.",
      interrogative: "Did they promise that they would call?",
    },
    {
      russian: "Если я выиграю в лотерею, я куплю дом.",
      english: "If I win the lottery, I will buy a house.",
      negative: "If I don't win the lottery, I won't buy a house.",
      interrogative: "If you win the lottery, will you buy a house?",
    },
    {
      russian: "Она должна была сказать мне.",
      english: "She ought to have told me.",
      negative: "She ought not to have told me.",
      interrogative: "Ought she to have told me?",
    },
    {
      russian: "Я не могу найти свой ключ.",
      english: "I am unable to find my key.",
      negative: "I am not unable to find my key.",
      interrogative: "Are you unable to find your key?",
    },
  ],
  [
    {
      russian: "Мы не успели на поезд, потому что он уже ушёл.",
      english: "We missed the train because it had already left.",
      negative: "We didn't miss the train because it had not left.",
      interrogative: "Did you miss the train because it had already left?",
    },
    {
      russian: "Я думаю, что он будет ждать нас.",
      english: "I think that he will be waiting for us.",
      negative: "I don't think that he will be waiting for us.",
      interrogative: "Do you think that he will be waiting for us?",
    },
    {
      russian: "Если бы ты позвонил, я бы пришёл.",
      english: "If you had called, I would have come.",
      negative: "If you had not called, I would not have come.",
      interrogative: "If you had called, would I have come?",
    },
    {
      russian: "Я должен был бы быть там сейчас.",
      english: "I should have been there by now.",
      negative: "I shouldn't have been there by now.",
      interrogative: "Should I have been there by now?",
    },
    {
      russian: "Они строили дом, когда начался дождь.",
      english: "They were building a house when it started to rain.",
      negative: "They were not building a house when it started to rain.",
      interrogative: "Were they building a house when it started to rain?",
    },
    {
      russian: "Я буду работать, пока ты отдыхаешь.",
      english: "I will be working while you are resting.",
      negative: "I won't be working while you are resting.",
      interrogative: "Will you be working while I am resting?",
    },
    {
      russian: "Она сказала, что приедет в следующем году.",
      english: "She said she would come the next year.",
      negative: "She didn't say she would come the next year.",
      interrogative: "Did she say she would come the next year?",
    },
    {
      russian: "Я мог бы жить здесь.",
      english: "I could live here.",
      negative: "I could not live here.",
      interrogative: "Could you live here?",
    },
    {
      russian: "Если бы я был богатым, я бы путешествовал.",
      english: "If I were rich, I would travel.",
      negative: "If I were not rich, I would not travel.",
      interrogative: "If you were rich, would you travel?",
    },
    {
      russian: "Ты должен был бы знать это.",
      english: "You must have known it.",
      negative: "You must not have known it.",
      interrogative: "Must you have known it?",
    },
  ],
  // --- УРОВЕНЬ 3: ПРОДВИНУТЫЙ (Phrasal verbs, idioms) ---
  [
    {
      russian: "Я не могу с этим мириться.",
      english: "I can't put up with this.",
      negative: "I can put up with this.",
      interrogative: "Can you put up with this?",
    },
    {
      russian: "Она нашла выход из ситуации.",
      english: "She figured out the situation.",
      negative: "She didn't figure out the situation.",
      interrogative: "Did she figure out the situation?",
    },
    {
      russian: "Мы не можем отказаться от этого.",
      english: "We can't back out of this.",
      negative: "We can back out of this.",
      interrogative: "Can you back out of this?",
    },
    {
      russian: "Он ждёт тебя с нетерпением.",
      english: "He is looking forward to seeing you.",
      negative: "He is not looking forward to seeing you.",
      interrogative: "Is he looking forward to seeing you?",
    },
    {
      russian: "Она придумала хорошую идею.",
      english: "She came up with a good idea.",
      negative: "She didn't come up with a good idea.",
      interrogative: "Did she come up with a good idea?",
    },
    {
      russian: "Ты должен принять решение.",
      english: "You have to make up your mind.",
      negative: "You don't have to make up your mind.",
      interrogative: "Do you have to make up your mind?",
    },
    {
      russian: "Они ушли из-за шума.",
      english: "They walked out because of the noise.",
      negative: "They didn't walk out because of the noise.",
      interrogative: "Did they walk out because of the noise?",
    },
    {
      russian: "Я наткнулся на старую фотографию.",
      english: "I came across an old photo.",
      negative: "I didn't come across an old photo.",
      interrogative: "Did you come across an old photo?",
    },
    {
      russian: "Я должен был вернуться.",
      english: "I had to go back.",
      negative: "I didn't have to go back.",
      interrogative: "Did you have to go back?",
    },
    {
      russian: "Он пытается бросить курить.",
      english: "He is trying to give up smoking.",
      negative: "He is not trying to give up smoking.",
      interrogative: "Is he trying to give up smoking?",
    },
  ],
  [
    {
      russian: "Мне нужно это выяснить.",
      english: "I need to find this out.",
      negative: "I don't need to find this out.",
      interrogative: "Do you need to find this out?",
    },
    {
      russian: "Я был шокирован, когда услышал новости.",
      english: "I was taken aback when I heard the news.",
      negative: "I was not taken aback when I heard the news.",
      interrogative: "Were you taken aback when you heard the news?",
    },
    {
      russian: "Он отказался от приглашения.",
      english: "He turned down the invitation.",
      negative: "He didn't turn down the invitation.",
      interrogative: "Did he turn down the invitation?",
    },
    {
      russian: "Мы должны придумать план.",
      english: "We need to come up with a plan.",
      negative: "We don't need to come up with a plan.",
      interrogative: "Do we need to come up with a plan?",
    },
    {
      russian: "Они отложили встречу.",
      english: "They put off the meeting.",
      negative: "They didn't put off the meeting.",
      interrogative: "Did they put off the meeting?",
    },
    {
      russian: "Я не могу с этим справиться.",
      english: "I can't cope with this.",
      negative: "I can cope with this.",
      interrogative: "Can you cope with this?",
    },
    {
      russian: "Она всегда поддерживает его.",
      english: "She always stands by him.",
      negative: "She never stands by him.",
      interrogative: "Does she always stand by him?",
    },
    {
      russian: "Мы должны поторопиться.",
      english: "We need to hurry up.",
      negative: "We don't need to hurry up.",
      interrogative: "Do we need to hurry up?",
    },
    {
      russian: "Он сделал это с лёгкостью.",
      english: "He did it with flying colors.",
      negative: "He didn't do it with flying colors.",
      interrogative: "Did he do it with flying colors?",
    },
    {
      russian: "Я в полном замешательстве.",
      english: "I am all at sea.",
      negative: "I am not all at sea.",
      interrogative: "Are you all at sea?",
    },
  ],
  [
    {
      russian: "Я с нетерпением жду нашего отпуска.",
      english: "I am looking forward to our vacation.",
      negative: "I am not looking forward to our vacation.",
      interrogative: "Are you looking forward to our vacation?",
    },
    {
      russian: "Они поссорились и теперь не разговаривают.",
      english: "They fell out and are not talking now.",
      negative: "They didn't fall out and are talking now.",
      interrogative: "Did they fall out and are they not talking now?",
    },
    {
      russian: "Мне нужно наверстать упущенное.",
      english: "I need to catch up on my work.",
      negative: "I don't need to catch up on my work.",
      interrogative: "Do you need to catch up on your work?",
    },
    {
      russian: "Он всегда говорит всё прямо.",
      english: "He always speaks his mind.",
      negative: "He never speaks his mind.",
      interrogative: "Does he always speak his mind?",
    },
    {
      russian: "Она всегда ищет компромисс.",
      english: "She always tries to meet halfway.",
      negative: "She never tries to meet halfway.",
      interrogative: "Does she always try to meet halfway?",
    },
    {
      russian: "Он подвёл меня в последний момент.",
      english: "He let me down at the last minute.",
      negative: "He didn't let me down at the last minute.",
      interrogative: "Did he let you down at the last minute?",
    },
    {
      russian: "Я должен привыкнуть к новым правилам.",
      english: "I have to get used to the new rules.",
      negative: "I don't have to get used to the new rules.",
      interrogative: "Do you have to get used to the new rules?",
    },
    {
      russian: "Это не стоит того.",
      english: "It's not worth it.",
      negative: "It is worth it.",
      interrogative: "Is it worth it?",
    },
    {
      russian: "Он не терял ни минуты.",
      english: "He didn't waste a second.",
      negative: "He wasted a second.",
      interrogative: "Did he waste a second?",
    },
    {
      russian: "Я хочу узнать больше об этом.",
      english: "I want to find out more about this.",
      negative: "I don't want to find out more about this.",
      interrogative: "Do you want to find out more about this?",
    },
  ],
  [
    {
      russian: "Давай встретимся в 8.",
      english: "Let's catch up at 8.",
      negative: "Let's not catch up at 8.",
      interrogative: "Shall we catch up at 8?",
    },
    {
      russian: "Мне нужно избавиться от старой мебели.",
      english: "I need to get rid of the old furniture.",
      negative: "I don't need to get rid of the old furniture.",
      interrogative: "Do you need to get rid of the old furniture?",
    },
    {
      russian: "Она бросила его.",
      english: "She broke up with him.",
      negative: "She didn't break up with him.",
      interrogative: "Did she break up with him?",
    },
    {
      russian: "Я надеюсь, ты не подведёшь меня.",
      english: "I hope you won't let me down.",
      negative: "I don't hope you will let me down.",
      interrogative: "Do you hope you won't let me down?",
    },
    {
      russian: "Ты всегда можешь на меня рассчитывать.",
      english: "You can always count on me.",
      negative: "You can't always count on me.",
      interrogative: "Can I always count on you?",
    },
    {
      russian: "Он не смог устоять перед искушением.",
      english: "He couldn't resist the temptation.",
      negative: "He could resist the temptation.",
      interrogative: "Could he resist the temptation?",
    },
    {
      russian: "Я наконец-то до него дозвонился.",
      english: "I finally got through to him.",
      negative: "I finally didn't get through to him.",
      interrogative: "Did you finally get through to him?",
    },
    {
      russian: "Это зависит от тебя.",
      english: "It's up to you.",
      negative: "It's not up to you.",
      interrogative: "Is it up to you?",
    },
    {
      russian: "Я буду держать тебя в курсе.",
      english: "I will keep you in the loop.",
      negative: "I won't keep you in the loop.",
      interrogative: "Will you keep me in the loop?",
    },
    {
      russian: "Мы должны взять тайм-аут.",
      english: "We need to take a break.",
      negative: "We don't need to take a break.",
      interrogative: "Do we need to take a break?",
    },
  ],
  [
    {
      russian: "Они помирились.",
      english: "They made up.",
      negative: "They didn't make up.",
      interrogative: "Did they make up?",
    },
    {
      russian: "Я перезвоню тебе позже.",
      english: "I will call you back later.",
      negative: "I will not call you back later.",
      interrogative: "Will you call me back later?",
    },
    {
      russian: "Он очень похож на своего отца.",
      english: "He takes after his father.",
      negative: "He doesn't take after his father.",
      interrogative: "Does he take after his father?",
    },
    {
      russian: "Я должен был справиться с этим сам.",
      english: "I had to deal with it on my own.",
      negative: "I didn't have to deal with it on my own.",
      interrogative: "Did you have to deal with it on your own?",
    },
    {
      russian: "Давай разберёмся в этом.",
      english: "Let's sort it out.",
      negative: "Let's not sort it out.",
      interrogative: "Shall we sort it out?",
    },
    {
      russian: "Я не могу больше терпеть это.",
      english: "I can't stand this any longer.",
      negative: "I can stand this any longer.",
      interrogative: "Can you stand this any longer?",
    },
    {
      russian: "Мы зашли в тупик.",
      english: "We reached a dead end.",
      negative: "We didn't reach a dead end.",
      interrogative: "Did you reach a dead end?",
    },
    {
      russian: "Это слишком дорого для меня.",
      english: "It costs an arm and a leg.",
      negative: "It doesn't cost an arm and a leg.",
      interrogative: "Does it cost an arm and a leg?",
    },
    {
      russian: "Я в восторге от этой идеи.",
      english: "I am over the moon about this idea.",
      negative: "I am not over the moon about this idea.",
      interrogative: "Are you over the moon about this idea?",
    },
    {
      russian: "Он сделал всё возможное.",
      english: "He went the extra mile.",
      negative: "He didn't go the extra mile.",
      interrogative: "Did he go the extra mile?",
    },
  ],
];
